#!/bin/sh
# MyMD: nightly guard for the "document filed but reaches nobody's inbox" family of failures.
#
# Every incident this week had the same shape: the chart link succeeded, the inbox routing silently
# did not, and nothing said so. This checks the three known ways that happens and emails
# info@mymdonline.ca (whose new-mail SMS bridge pages the phone) ONLY when something is wrong.
#
# Runs as root from cron: `mysql` uses socket auth, msmtp reads root's /etc/msmtprc (account mymd).
# Deliberately PHI-free: document numbers, types and counts - no names, no descriptions.
#
# Installed at /usr/local/bin/mymd_routing_check.sh; cron entry in root's crontab.
# Source of truth: docs/oscar/fax-triage/ in the patient-intake-2 repo.

set -u
ALERT=""
add() { ALERT="${ALERT}${1}
"; }

# NOTE: alert text must stay plain ASCII - the first live email rendered an em-dash as "â€""
# in Roundcube because msmtp sends no charset header. The header below declares UTF-8 anyway,
# but ASCII-only is what makes it robust everywhere (including the SMS bridge).

# 1. The MySQL 8 regression that broke ALL routing inserts until 2026-08-11. A WAR redeploy or a
#    MySQL upgrade can flip it back, and its only symptom is documents quietly reaching nobody.
V=$(mysql -N -e "SELECT @@global.explicit_defaults_for_timestamp" 2>/dev/null)
[ "$V" = "1" ] && add "CRITICAL: explicit_defaults_for_timestamp is back ON - every inbox-routing insert is failing again. Fix: SET PERSIST explicit_defaults_for_timestamp = OFF; then restart tomcat9. See reference_oscar_mysql8_timestamp_null."

# 2. Labs whose ONLY routing rows point at nobody ('' or a nonexistent provider) - those labs
#    appear in NO inbox, which is the failure this guard exists for. A stray ''-row on a lab
#    that ALSO reached a real provider is a harmless duplicate (minted by the ''-MRP import
#    quirk) and is deliberately not alerted on: not every patient has an MRP, and those labs
#    did reach an inbox. (Narrowed 2026-08-28 after two benign duplicates paged the phone.)
LOST=$(mysql -N oscar_db -e "
  SELECT GROUP_CONCAT(DISTINCT CONCAT(r.lab_type, ' lab_no ', r.lab_no) SEPARATOR ', ')
  FROM providerLabRouting r
  LEFT JOIN provider p ON p.provider_no = r.provider_no
  WHERE p.provider_no IS NULL
    AND NOT EXISTS (
      SELECT 1 FROM providerLabRouting r2
      JOIN provider p2 ON p2.provider_no = r2.provider_no
      WHERE r2.lab_no = r.lab_no AND r2.lab_type = r.lab_type)" 2>/dev/null)
[ -n "$LOST" ] && [ "$LOST" != "NULL" ] && add "WARNING: lab(s) routed only to a provider that does not exist - they appear in NO inbox: $LOST. Route them from the lab display (Flag Provider) or fix the rows in providerLabRouting."

# 3. Charts spelling 'no MRP' as '' instead of NULL - the spelling OSCAR's lab router does not
#    guard, which mints the rows in check 2 on every Lab Import. (Clinic policy: MRP is only set
#    when a physician accepts the patient, so NULL is the correct state - never backfill.)
EMPTY=$(mysql -N oscar_db -e "SELECT COUNT(*) FROM demographic WHERE provider_no=''" 2>/dev/null)
[ "${EMPTY:-0}" -gt 0 ] && add "WARNING: $EMPTY chart(s) have provider_no='' (should be NULL). Fix: UPDATE demographic SET provider_no=NULL WHERE provider_no='';"

# (A fourth check - documents filed to a chart with no inbox routing at all - was removed
# 2026-08-23 at the physician's request: staff file documents they have already reviewed,
# so the alert was pure noise.)

[ -z "$ALERT" ] && exit 0

printf 'To: info@mymdonline.ca\nFrom: info@mymdonline.ca\nSubject: OSCAR routing check: action needed\nMIME-Version: 1.0\nContent-Type: text/plain; charset=UTF-8\n\n%s\nGenerated by /usr/local/bin/mymd_routing_check.sh on the OSCAR server.\n' "$ALERT" \
  | msmtp -a mymd info@mymdonline.ca
