import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div
          aria-hidden="true"
          className={[
            "pointer-events-none fixed left-0 top-0 z-50 select-none",
            // Keep readable without impacting page layouts; also respect iOS safe-area insets.
            "text-xs font-semibold tracking-wide text-slate-600",
            "pt-[calc(env(safe-area-inset-top)+0.5rem)] pb-2 pr-4",
            "pl-[calc(env(safe-area-inset-left)+1rem)]",
          ].join(" ")}
        >
          Health Assist AI
        </div>
        {children}
      </body>
    </html>
  );
}
