// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin/dashboard" | "/admin/login" | "/admin/organizations/[id]" | "/admin/organizations/[id]/providers/[providerId]/edit" | "/admin/organizations/[id]/providers/new" | "/admin/organizations/new" | "/admin/register-physician" | "/auth/login" | "/auth/signin" | "/intake/[slug]" | "/org/dashboard" | "/org/login" | "/org/providers/[id]/edit" | "/org/providers/new" | "/physician/dashboard" | "/physician/generate-link" | "/physician/view"
type AppRouteHandlerRoutes = "/api/admin/organizations" | "/api/admin/organizations/[id]" | "/api/admin/providers" | "/api/admin/providers/[id]" | "/api/analyze-lesion" | "/api/auth/[...nextauth]" | "/api/auth/login" | "/api/auth/logout" | "/api/auth/me" | "/api/auth/register" | "/api/auth/reset-password" | "/api/auth/reset-password/[token]" | "/api/history" | "/api/interview" | "/api/invitations/send" | "/api/org/organization" | "/api/org/providers" | "/api/org/providers/[id]" | "/api/pharmacy" | "/api/physicians/by-slug/[slug]" | "/api/sessions" | "/api/sessions/list"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin/dashboard": {}
  "/admin/login": {}
  "/admin/organizations/[id]": { "id": string; }
  "/admin/organizations/[id]/providers/[providerId]/edit": { "id": string; "providerId": string; }
  "/admin/organizations/[id]/providers/new": { "id": string; }
  "/admin/organizations/new": {}
  "/admin/register-physician": {}
  "/api/admin/organizations": {}
  "/api/admin/organizations/[id]": { "id": string; }
  "/api/admin/providers": {}
  "/api/admin/providers/[id]": { "id": string; }
  "/api/analyze-lesion": {}
  "/api/auth/[...nextauth]": { "nextauth": string[]; }
  "/api/auth/login": {}
  "/api/auth/logout": {}
  "/api/auth/me": {}
  "/api/auth/register": {}
  "/api/auth/reset-password": {}
  "/api/auth/reset-password/[token]": { "token": string; }
  "/api/history": {}
  "/api/interview": {}
  "/api/invitations/send": {}
  "/api/org/organization": {}
  "/api/org/providers": {}
  "/api/org/providers/[id]": { "id": string; }
  "/api/pharmacy": {}
  "/api/physicians/by-slug/[slug]": { "slug": string; }
  "/api/sessions": {}
  "/api/sessions/list": {}
  "/auth/login": {}
  "/auth/signin": {}
  "/intake/[slug]": { "slug": string; }
  "/org/dashboard": {}
  "/org/login": {}
  "/org/providers/[id]/edit": { "id": string; }
  "/org/providers/new": {}
  "/physician/dashboard": {}
  "/physician/generate-link": {}
  "/physician/view": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
