// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../src/app/admin/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/dashboard">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/login">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/organizations/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/organizations/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/organizations/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/organizations/[id]/providers/[providerId]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/organizations/[id]/providers/[providerId]/edit">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/organizations/[id]/providers/[providerId]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/organizations/[id]/providers/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/organizations/[id]/providers/new">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/organizations/[id]/providers/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/organizations/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/organizations/new">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/organizations/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/register-physician/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/register-physician">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/register-physician/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/auth/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/login">> = Specific
  const handler = {} as typeof import("../../../src/app/auth/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/auth/signin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/signin">> = Specific
  const handler = {} as typeof import("../../../src/app/auth/signin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/intake/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/intake/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/intake/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/org/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/org/dashboard">> = Specific
  const handler = {} as typeof import("../../../src/app/org/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/org/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/org/login">> = Specific
  const handler = {} as typeof import("../../../src/app/org/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/org/providers/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/org/providers/[id]/edit">> = Specific
  const handler = {} as typeof import("../../../src/app/org/providers/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/org/providers/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/org/providers/new">> = Specific
  const handler = {} as typeof import("../../../src/app/org/providers/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/physician/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/physician/dashboard">> = Specific
  const handler = {} as typeof import("../../../src/app/physician/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/physician/generate-link/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/physician/generate-link">> = Specific
  const handler = {} as typeof import("../../../src/app/physician/generate-link/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/physician/view/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/physician/view">> = Specific
  const handler = {} as typeof import("../../../src/app/physician/view/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/organizations/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/organizations/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/organizations/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/organizations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/organizations">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/organizations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/providers/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/providers/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/providers/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/providers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/providers">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/providers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/analyze-lesion/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/analyze-lesion">> = Specific
  const handler = {} as typeof import("../../../src/app/api/analyze-lesion/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/[...nextauth]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/[...nextauth]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/[...nextauth]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/login">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/logout">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/me/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/me">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/me/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/register/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/register">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/register/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/reset-password/[token]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/reset-password/[token]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/reset-password/[token]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/reset-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/reset-password">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/reset-password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/history/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/history">> = Specific
  const handler = {} as typeof import("../../../src/app/api/history/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/interview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/interview">> = Specific
  const handler = {} as typeof import("../../../src/app/api/interview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/invitations/send/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/invitations/send">> = Specific
  const handler = {} as typeof import("../../../src/app/api/invitations/send/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/org/organization/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/org/organization">> = Specific
  const handler = {} as typeof import("../../../src/app/api/org/organization/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/org/providers/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/org/providers/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/org/providers/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/org/providers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/org/providers">> = Specific
  const handler = {} as typeof import("../../../src/app/api/org/providers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/pharmacy/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pharmacy">> = Specific
  const handler = {} as typeof import("../../../src/app/api/pharmacy/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/physicians/by-slug/[slug]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/physicians/by-slug/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/physicians/by-slug/[slug]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/sessions/list/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sessions/list">> = Specific
  const handler = {} as typeof import("../../../src/app/api/sessions/list/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/sessions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sessions">> = Specific
  const handler = {} as typeof import("../../../src/app/api/sessions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
